LT-Students/DigitalOffice-ProjectService

.github/workflows/main.yml
remove check push in branches  - feature/*
=> Fix action

src/ProjectService/ProjectService.csproj, src/ProjectService/Startup.cs
What need to be done
1. Remove UseHealthChecks()
2. Map healthcheck endpoint to '/{serviceID}/hc'
3. Add RabbitMQ healthcheck
4. Add SQL Server healthcheck
4. Rework healthcheck endpoint response
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/250
=> Feature #250 Update healthcheck

src/ProjectService.Models.Broker/Models/UserData.cs, test/ProjectService.Business.UnitTests/Commands/FindTasksCommandTests.cs, test/ProjectService.Business.UnitTests/Commands/GetProjectCommandTests.cs, test/ProjectService.Mappers.UnitTests/Models/ProjectUserInfoMapperTests.cs, test/ProjectService.Mappers.UnitTests/Models/TaskInfoMapperTests.cs
https://github.com/LT-Students/DigitalOffice-UserService/pull/52
=> Remove set from broker model

src/ProjectService.Business/Commands/Task/CreateTaskCommand.cs, src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210707003534_ChangeTaskPropertiesTableColumn.cs, src/ProjectService.Mappers/RequestsMappers/DbTaskMapper.cs, src/ProjectService.Mappers/RequestsMappers/Interfaces/IDbProjectMapper.cs, src/ProjectService.Mappers/RequestsMappers/Interfaces/IDbTaskMapper.cs, src/ProjectService.Mappers/RequestsMappers/Interfaces/IPatchDbTaskMapper.cs, src/ProjectService.Models.Db/DbTask.cs, src/ProjectService.Models.Dto/Requests/CreateTaskRequest.cs, src/ProjectService.Validation/CreateProjectValidator.cs, src/ProjectService.Validation/CreateTaskRequestValidator.cs, src/ProjectService.Validation/ProjectUserValidator.cs, test/ProjectService.Business.UnitTests/Commands/CreateTaskCommandTests.cs, test/ProjectService.Mappers.UnitTests/RequestsMappers/DbTaskMapperTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/750?issue_count=2&issue_position=1&next_issue_id=639
=> Fix create task

src/ProjectService.Business/Commands/AddUsersToProjectCommand.cs, src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210711203811_FixForeignKey.cs, src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210711203811_RemoveForeignKey.cs, src/ProjectService.Data/UserRepository.cs, src/ProjectService.Validation/AddUsersToProjectValidator.cs, test/ProjectService.Data.UnitTests/AddUsersToProjectRepositoryTests.cs, test/ProjectService.Validation.UnitTests/AddUsersToProjectValidatorTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/776
=> fix user/AddUsersToProject

src/ProjectService/Program.cs, src/ProjectService/appsettings.Development.json, src/ProjectService/appsettings.Production.json, src/ProjectService/appsettings.json
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/655
=> change logger config

Common.Configurations.targets, src/ProjectService.Broker/GetDepartmentProjectsConsumer.cs, src/ProjectService.Data/Interfaces/IProjectRepository.cs, src/ProjectService.Data/ProjectRepository.cs, src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs, src/ProjectService/Startup.cs, src/ProjectService/appsettings.json, test/ProjectService.Business.UnitTests/Commands/FindTasksCommandTests.cs, test/ProjectService.Business.UnitTests/Commands/GetProjectCommandTests.cs, test/ProjectService.Mappers.UnitTests/Models/ProjectUserInfoMapperTests.cs, test/ProjectService.Mappers.UnitTests/Models/TaskInfoMapperTests.cs, test/ProjectService.Mappers.UnitTests/Responses/TaskResponseMapperTests.cs
=> Add GetDepartmentProjectsConsumer

Common.Configurations.targets, src/ProjectService.Business/Commands/FindProjectsCommand.cs
update models service and model
=> fix find project command

src/ProjectService.Business/Commands/Task/EditTaskCommand.cs, src/ProjectService.Validation/EditTaskValidator.cs, src/ProjectService/Controllers/TaskController.cs, test/ProjectService.Business.UnitTests/Commands/EditTaskCommandTests.cs
problems with validation, cannot cast value to (Guid or int)
=> fix edit task

src/ProjectService.Business/Commands/Project/CreateProjectCommand.cs, src/ProjectService.Business/Commands/Project/EditProjectCommand.cs, src/ProjectService.Business/Commands/Project/FindProjectsCommand.cs, src/ProjectService.Business/Commands/Project/GetProjectCommand.cs, src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210730140500_UpdateProjectsTable.cs, src/ProjectService.Mappers/Models/ProjectInfoMapper.cs, src/ProjectService.Mappers/Responses/FindProjectsResponseMapper.cs, src/ProjectService.Models.Db/DbProject.cs, src/ProjectService.Models.Dto/Requests/ProjectRequest.cs, src/ProjectService.Validation/CreateProjectValidator.cs, test/ProjectService.Data.UnitTests/FindProjectRepositoryTests.cs, test/ProjectService.Mappers.UnitTests/Models/ProjectInfoMapperTests.cs, test/ProjectService.Mappers.UnitTests/ProjectInfoMapperTests.cs, test/ProjectService.Mappers.UnitTests/Responses/FindProjectsResponseMapperTests.cs, test/ProjectService.Mappers.UnitTests/Responses/ProjectResponseMapperTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/819
=> make department nullable for project

Common.Configurations.targets, src/ProjectService.Models.Db/DbProject.cs, src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs, src/ProjectService/Startup.cs, src/ProjectService/appsettings.json
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/728
=> add find entity consumer

src/ProjectService.Data/TaskRepository.cs, src/ProjectService.Models.Dto/Requests/Filters/FindTasksFilter.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/826
=> add filter for status

Common.Configurations.targets, src/ProjectService.Broker/GetProjectsUsersConsumer.cs, src/ProjectService.Business/Commands/Project/CreateProjectCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/AddUsersToProjectCommand.cs, src/ProjectService.Data/Interfaces/IProjectRepository.cs, src/ProjectService.Data/ProjectRepository.cs, src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs, src/ProjectService/Startup.cs, src/ProjectService/appsettings.json, test/ProjectService.Business.UnitTests/Commands/AddUsersToProjectCommandTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/835
=> add consumer and rc to commands

src/ProjectService.Business/Commands/Task/EditTaskCommand.cs, test/ProjectService.Business.UnitTests/Commands/EditTaskCommandTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/830
=> rework access validator

Common.Configurations.targets, src/ProjectService.Business/Commands/Project/GetProjectCommand.cs, src/ProjectService.Business/Commands/Project/Interfaces/IGetProjectCommand.cs, src/ProjectService.Mappers/Responses/Interfaces/IProjectResponseMapper.cs, src/ProjectService.Mappers/Responses/ProjectResponseMapper.cs, src/ProjectService.Models.Dto/Responses/ProjectResponse.cs, src/ProjectService/Controllers/ProjectController.cs, test/ProjectService.Mappers.UnitTests/Responses/ProjectResponseMapperTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/840
=> rework getProject response

.github/workflows/main.yml, Common.Configurations.targets, Dockerfile, src/ProjectService.Broker/GetProjectUsersConsumer.cs, src/ProjectService.Data/UserRepository.cs, src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs, src/ProjectService/Startup.cs, src/ProjectService/appsettings.json
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/850
=> add consumer get project users

Common.Configurations.targets, src/ProjectService.Broker/DisactivateProjectUserConsumer.cs, src/ProjectService.Broker/GetProjectsConsumer.cs, src/ProjectService.Business/Commands/Project/EditProjectCommand.cs, src/ProjectService.Business/Commands/Project/FindProjectsCommand.cs, src/ProjectService.Business/Commands/Project/GetProjectCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/CreateProjectUsersCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/RemoveProjectUsersCommand.cs, src/ProjectService.Data/Interfaces/IUserRepository.cs, src/ProjectService.Data/UserRepository.cs, src/ProjectService/ProjectService.csproj, src/ProjectService/Startup.cs, src/ProjectService/appsettings.Development.json
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/989
=> update redis methods

Common.Configurations.targets, src/ProjectService.Broker/Consumers/GetProjectsConsumer.cs
Removed DepartmentId from IGetProjectsRequest
=> new Models-NuGet version 1.0.84

src/ProjectService.Broker/Requests/Interfaces/IUserService.cs, src/ProjectService.Broker/Requests/UserService.cs, src/ProjectService.Validation/Project/CreateProjectRequestValidator.cs, src/ProjectService.Validation/ProjectService.Validation.csproj, src/ProjectService.Validation/User/AddUsersToProjectValidator.cs
Added to Broker.Requests.UserService CheckUsersExistenceAsync method and changed RuleFor check in CreateProjectRequestValidator and in AddUsersToProjectValidator
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/1034
=> add check users existence to validator

src/ProjectService.Broker/Requests/ImageService.cs, src/ProjectService.Broker/Requests/Interfaces/IImageService.cs, src/ProjectService.Broker/Requests/Interfaces/IPositionService.cs, src/ProjectService.Broker/Requests/Interfaces/IUserService.cs, src/ProjectService.Broker/Requests/PositionService.cs, src/ProjectService.Broker/Requests/UserService.cs, src/ProjectService.Business/Commands/Project/GetProjectCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/FindProjectUsersCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/Interfaces/IFindProjectUsersCommand.cs, src/ProjectService.Data/Interfaces/IProjectRepository.cs, src/ProjectService.Data/Interfaces/IProjectUserRepository.cs, src/ProjectService.Data/ProjectRepository.cs, src/ProjectService.Data/ProjectUserRepository.cs, src/ProjectService.Mappers/Responses/Interfaces/IProjectResponseMapper.cs, src/ProjectService.Mappers/Responses/ProjectResponseMapper.cs, src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs, src/ProjectService.Models.Dto/Requests/Filters/FindProjectUsersFilter.cs, src/ProjectService.Models.Dto/Requests/Filters/GetProjectFilter.cs, src/ProjectService.Models.Dto/Responses/ProjectResponse.cs, src/ProjectService/Controllers/UserController.cs, src/ProjectService/Startup.cs, src/ProjectService/appsettings.json, test/ProjectService.Mappers.UnitTests/Responses/ProjectResponseMapperTests.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/1086
=> add find users endpoint

Common.Configurations.targets, src/ProjectService.Broker/Consumers/GetProjectsConsumer.cs, src/ProjectService.Data/ProjectRepository.cs, src/ProjectService.Mappers/Models/Interfaces/IProjectDepartmentDataMapper.cs, src/ProjectService.Mappers/Models/ProjectDepartmentDataMapper.cs
http://outsourcing.nat.tepkom.ru:20080/redmine/issues/1115
=> update GetProjects consumer

src/ProjectService.Data/ProjectRepository.cs
https://trello.com/c/rLhvjA0b/380-bugbe-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BD%D0%B5-%D0%BC%D0%BE%D0%B6%D0%B5%D1%82-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0
=> fix GetProjectWithUserAsync

Common.Configurations.targets, src/ProjectService.Broker/Requests/ImageService.cs, src/ProjectService.Broker/Requests/Interfaces/IImageService.cs, src/ProjectService.Broker/Requests/Interfaces/IPositionService.cs, src/ProjectService.Broker/Requests/Interfaces/IUserService.cs, src/ProjectService.Broker/Requests/PositionService.cs, src/ProjectService.Broker/Requests/UserService.cs, src/ProjectService.Business/Commands/File/FindFilesCommand.cs, src/ProjectService.Business/Commands/Project/FindProjectsCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/FindProjectUsersCommand.cs, src/ProjectService.Business/Commands/ProjectUsers/Interfaces/IFindProjectUsersCommand.cs, src/ProjectService.Data/Interfaces/IProjectUserRepository.cs, src/ProjectService.Data/ProjectUserRepository.cs, src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs, src/ProjectService.Models.Dto/Requests/User/FindProjectUsersFilter.cs, src/ProjectService/Controllers/UserController.cs, src/ProjectService/Startup.cs, src/ProjectService/appsettings.json, test/ProjectService.Business.UnitTests/Commands/Project/FindProjectsCommandTests.cs, test/ProjectService.Business.UnitTests/Commands/ProjectUsers/FindProjectUsersCommandTests.cs, test/ProjectService.Data.UnitTests/ProjectUserRepositoryTests.cs
updated Kernel version, removed BaseFindFilterValidation
=> added filter by name and position to User/find;

Common.Configurations.targets, src/ProjectService.Data/ProjectUserRepository.cs
=> add isActive to GetProjectUsers
